packages:
  - apps/*
  - packages/*

catalog:
  convex: 1.37.0
  typescript: 6.0.3

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@sentry/cli'
  - browser-tabs-lock
  - bufferutil
  - core-js
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
  - utf-8-validate
  - workerd
