/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PayRouteImport } from './routes/pay'
import { Route as MeRouteImport } from './routes/me'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RacesIndexRouteImport } from './routes/races/index'
import { Route as LeaguesIndexRouteImport } from './routes/leagues/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RacesRaceSlugRouteImport } from './routes/races/$raceSlug'
import { Route as PUsernameRouteImport } from './routes/p/$username'
import { Route as LeaguesCreateRouteImport } from './routes/leagues/create'
import { Route as LeaguesSlugRouteImport } from './routes/leagues/$slug'
import { Route as PUsernameFollowingRouteImport } from './routes/p/$username/following'
import { Route as PUsernameFollowersRouteImport } from './routes/p/$username/followers'
import { Route as LeaguesSlugSettingsRouteImport } from './routes/leagues/$slug/settings'
import { Route as AdminRacesRaceIdRouteImport } from './routes/admin/races/$raceId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesIndexRoute = RacesIndexRouteImport.update({
  id: '/races/',
  path: '/races/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesIndexRoute = LeaguesIndexRouteImport.update({
  id: '/leagues/',
  path: '/leagues/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesRaceSlugRoute = RacesRaceSlugRouteImport.update({
  id: '/races/$raceSlug',
  path: '/races/$raceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PUsernameRoute = PUsernameRouteImport.update({
  id: '/p/$username',
  path: '/p/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesCreateRoute = LeaguesCreateRouteImport.update({
  id: '/leagues/create',
  path: '/leagues/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesSlugRoute = LeaguesSlugRouteImport.update({
  id: '/leagues/$slug',
  path: '/leagues/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PUsernameFollowingRoute = PUsernameFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => PUsernameRoute,
} as any)
const PUsernameFollowersRoute = PUsernameFollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => PUsernameRoute,
} as any)
const LeaguesSlugSettingsRoute = LeaguesSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LeaguesSlugRoute,
} as any)
const AdminRacesRaceIdRoute = AdminRacesRaceIdRouteImport.update({
  id: '/admin/races/$raceId',
  path: '/admin/races/$raceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/me': typeof MeRoute
  '/pay': typeof PayRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/leagues/$slug': typeof LeaguesSlugRouteWithChildren
  '/leagues/create': typeof LeaguesCreateRoute
  '/p/$username': typeof PUsernameRouteWithChildren
  '/races/$raceSlug': typeof RacesRaceSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/leagues/': typeof LeaguesIndexRoute
  '/races/': typeof RacesIndexRoute
  '/admin/races/$raceId': typeof AdminRacesRaceIdRoute
  '/leagues/$slug/settings': typeof LeaguesSlugSettingsRoute
  '/p/$username/followers': typeof PUsernameFollowersRoute
  '/p/$username/following': typeof PUsernameFollowingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/me': typeof MeRoute
  '/pay': typeof PayRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/leagues/$slug': typeof LeaguesSlugRouteWithChildren
  '/leagues/create': typeof LeaguesCreateRoute
  '/p/$username': typeof PUsernameRouteWithChildren
  '/races/$raceSlug': typeof RacesRaceSlugRoute
  '/admin': typeof AdminIndexRoute
  '/leagues': typeof LeaguesIndexRoute
  '/races': typeof RacesIndexRoute
  '/admin/races/$raceId': typeof AdminRacesRaceIdRoute
  '/leagues/$slug/settings': typeof LeaguesSlugSettingsRoute
  '/p/$username/followers': typeof PUsernameFollowersRoute
  '/p/$username/following': typeof PUsernameFollowingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/me': typeof MeRoute
  '/pay': typeof PayRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/leagues/$slug': typeof LeaguesSlugRouteWithChildren
  '/leagues/create': typeof LeaguesCreateRoute
  '/p/$username': typeof PUsernameRouteWithChildren
  '/races/$raceSlug': typeof RacesRaceSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/leagues/': typeof LeaguesIndexRoute
  '/races/': typeof RacesIndexRoute
  '/admin/races/$raceId': typeof AdminRacesRaceIdRoute
  '/leagues/$slug/settings': typeof LeaguesSlugSettingsRoute
  '/p/$username/followers': typeof PUsernameFollowersRoute
  '/p/$username/following': typeof PUsernameFollowingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/me'
    | '/pay'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/settings'
    | '/support'
    | '/terms'
    | '/leagues/$slug'
    | '/leagues/create'
    | '/p/$username'
    | '/races/$raceSlug'
    | '/admin/'
    | '/leagues/'
    | '/races/'
    | '/admin/races/$raceId'
    | '/leagues/$slug/settings'
    | '/p/$username/followers'
    | '/p/$username/following'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/me'
    | '/pay'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/settings'
    | '/support'
    | '/terms'
    | '/leagues/$slug'
    | '/leagues/create'
    | '/p/$username'
    | '/races/$raceSlug'
    | '/admin'
    | '/leagues'
    | '/races'
    | '/admin/races/$raceId'
    | '/leagues/$slug/settings'
    | '/p/$username/followers'
    | '/p/$username/following'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/me'
    | '/pay'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/settings'
    | '/support'
    | '/terms'
    | '/leagues/$slug'
    | '/leagues/create'
    | '/p/$username'
    | '/races/$raceSlug'
    | '/admin/'
    | '/leagues/'
    | '/races/'
    | '/admin/races/$raceId'
    | '/leagues/$slug/settings'
    | '/p/$username/followers'
    | '/p/$username/following'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MeRoute: typeof MeRoute
  PayRoute: typeof PayRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  LeaguesSlugRoute: typeof LeaguesSlugRouteWithChildren
  LeaguesCreateRoute: typeof LeaguesCreateRoute
  PUsernameRoute: typeof PUsernameRouteWithChildren
  RacesRaceSlugRoute: typeof RacesRaceSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LeaguesIndexRoute: typeof LeaguesIndexRoute
  RacesIndexRoute: typeof RacesIndexRoute
  AdminRacesRaceIdRoute: typeof AdminRacesRaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races/': {
      id: '/races/'
      path: '/races'
      fullPath: '/races/'
      preLoaderRoute: typeof RacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/': {
      id: '/leagues/'
      path: '/leagues'
      fullPath: '/leagues/'
      preLoaderRoute: typeof LeaguesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races/$raceSlug': {
      id: '/races/$raceSlug'
      path: '/races/$raceSlug'
      fullPath: '/races/$raceSlug'
      preLoaderRoute: typeof RacesRaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$username': {
      id: '/p/$username'
      path: '/p/$username'
      fullPath: '/p/$username'
      preLoaderRoute: typeof PUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/create': {
      id: '/leagues/create'
      path: '/leagues/create'
      fullPath: '/leagues/create'
      preLoaderRoute: typeof LeaguesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$slug': {
      id: '/leagues/$slug'
      path: '/leagues/$slug'
      fullPath: '/leagues/$slug'
      preLoaderRoute: typeof LeaguesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$username/following': {
      id: '/p/$username/following'
      path: '/following'
      fullPath: '/p/$username/following'
      preLoaderRoute: typeof PUsernameFollowingRouteImport
      parentRoute: typeof PUsernameRoute
    }
    '/p/$username/followers': {
      id: '/p/$username/followers'
      path: '/followers'
      fullPath: '/p/$username/followers'
      preLoaderRoute: typeof PUsernameFollowersRouteImport
      parentRoute: typeof PUsernameRoute
    }
    '/leagues/$slug/settings': {
      id: '/leagues/$slug/settings'
      path: '/settings'
      fullPath: '/leagues/$slug/settings'
      preLoaderRoute: typeof LeaguesSlugSettingsRouteImport
      parentRoute: typeof LeaguesSlugRoute
    }
    '/admin/races/$raceId': {
      id: '/admin/races/$raceId'
      path: '/admin/races/$raceId'
      fullPath: '/admin/races/$raceId'
      preLoaderRoute: typeof AdminRacesRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LeaguesSlugRouteChildren {
  LeaguesSlugSettingsRoute: typeof LeaguesSlugSettingsRoute
}

const LeaguesSlugRouteChildren: LeaguesSlugRouteChildren = {
  LeaguesSlugSettingsRoute: LeaguesSlugSettingsRoute,
}

const LeaguesSlugRouteWithChildren = LeaguesSlugRoute._addFileChildren(
  LeaguesSlugRouteChildren,
)

interface PUsernameRouteChildren {
  PUsernameFollowersRoute: typeof PUsernameFollowersRoute
  PUsernameFollowingRoute: typeof PUsernameFollowingRoute
}

const PUsernameRouteChildren: PUsernameRouteChildren = {
  PUsernameFollowersRoute: PUsernameFollowersRoute,
  PUsernameFollowingRoute: PUsernameFollowingRoute,
}

const PUsernameRouteWithChildren = PUsernameRoute._addFileChildren(
  PUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  MeRoute: MeRoute,
  PayRoute: PayRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  LeaguesSlugRoute: LeaguesSlugRouteWithChildren,
  LeaguesCreateRoute: LeaguesCreateRoute,
  PUsernameRoute: PUsernameRouteWithChildren,
  RacesRaceSlugRoute: RacesRaceSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  LeaguesIndexRoute: LeaguesIndexRoute,
  RacesIndexRoute: RacesIndexRoute,
  AdminRacesRaceIdRoute: AdminRacesRaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
