/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MeRouteImport } from './routes/me'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RacesIndexRouteImport } from './routes/races/index'
import { Route as LeaguesIndexRouteImport } from './routes/leagues/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RacesRaceIdRouteImport } from './routes/races/$raceId'
import { Route as PUsernameRouteImport } from './routes/p/$username'
import { Route as LeaguesSlugRouteImport } from './routes/leagues/$slug'
import { Route as AdminRacesNewRouteImport } from './routes/admin/races/new'
import { Route as AdminRacesRaceIdRouteImport } from './routes/admin/races/$raceId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesIndexRoute = RacesIndexRouteImport.update({
  id: '/races/',
  path: '/races/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesIndexRoute = LeaguesIndexRouteImport.update({
  id: '/leagues/',
  path: '/leagues/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesRaceIdRoute = RacesRaceIdRouteImport.update({
  id: '/races/$raceId',
  path: '/races/$raceId',
  getParentRoute: () => rootRouteImport,
} as any)
const PUsernameRoute = PUsernameRouteImport.update({
  id: '/p/$username',
  path: '/p/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesSlugRoute = LeaguesSlugRouteImport.update({
  id: '/leagues/$slug',
  path: '/leagues/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRacesNewRoute = AdminRacesNewRouteImport.update({
  id: '/admin/races/new',
  path: '/admin/races/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRacesRaceIdRoute = AdminRacesRaceIdRouteImport.update({
  id: '/admin/races/$raceId',
  path: '/admin/races/$raceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/me': typeof MeRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/leagues/$slug': typeof LeaguesSlugRoute
  '/p/$username': typeof PUsernameRoute
  '/races/$raceId': typeof RacesRaceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/leagues/': typeof LeaguesIndexRoute
  '/races/': typeof RacesIndexRoute
  '/admin/races/$raceId': typeof AdminRacesRaceIdRoute
  '/admin/races/new': typeof AdminRacesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/me': typeof MeRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/leagues/$slug': typeof LeaguesSlugRoute
  '/p/$username': typeof PUsernameRoute
  '/races/$raceId': typeof RacesRaceIdRoute
  '/admin': typeof AdminIndexRoute
  '/leagues': typeof LeaguesIndexRoute
  '/races': typeof RacesIndexRoute
  '/admin/races/$raceId': typeof AdminRacesRaceIdRoute
  '/admin/races/new': typeof AdminRacesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/me': typeof MeRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/leagues/$slug': typeof LeaguesSlugRoute
  '/p/$username': typeof PUsernameRoute
  '/races/$raceId': typeof RacesRaceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/leagues/': typeof LeaguesIndexRoute
  '/races/': typeof RacesIndexRoute
  '/admin/races/$raceId': typeof AdminRacesRaceIdRoute
  '/admin/races/new': typeof AdminRacesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/me'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/leagues/$slug'
    | '/p/$username'
    | '/races/$raceId'
    | '/admin/'
    | '/leagues/'
    | '/races/'
    | '/admin/races/$raceId'
    | '/admin/races/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/me'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/leagues/$slug'
    | '/p/$username'
    | '/races/$raceId'
    | '/admin'
    | '/leagues'
    | '/races'
    | '/admin/races/$raceId'
    | '/admin/races/new'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/me'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/leagues/$slug'
    | '/p/$username'
    | '/races/$raceId'
    | '/admin/'
    | '/leagues/'
    | '/races/'
    | '/admin/races/$raceId'
    | '/admin/races/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MeRoute: typeof MeRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  LeaguesSlugRoute: typeof LeaguesSlugRoute
  PUsernameRoute: typeof PUsernameRoute
  RacesRaceIdRoute: typeof RacesRaceIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LeaguesIndexRoute: typeof LeaguesIndexRoute
  RacesIndexRoute: typeof RacesIndexRoute
  AdminRacesRaceIdRoute: typeof AdminRacesRaceIdRoute
  AdminRacesNewRoute: typeof AdminRacesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races/': {
      id: '/races/'
      path: '/races'
      fullPath: '/races/'
      preLoaderRoute: typeof RacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/': {
      id: '/leagues/'
      path: '/leagues'
      fullPath: '/leagues/'
      preLoaderRoute: typeof LeaguesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races/$raceId': {
      id: '/races/$raceId'
      path: '/races/$raceId'
      fullPath: '/races/$raceId'
      preLoaderRoute: typeof RacesRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$username': {
      id: '/p/$username'
      path: '/p/$username'
      fullPath: '/p/$username'
      preLoaderRoute: typeof PUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$slug': {
      id: '/leagues/$slug'
      path: '/leagues/$slug'
      fullPath: '/leagues/$slug'
      preLoaderRoute: typeof LeaguesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/races/new': {
      id: '/admin/races/new'
      path: '/admin/races/new'
      fullPath: '/admin/races/new'
      preLoaderRoute: typeof AdminRacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/races/$raceId': {
      id: '/admin/races/$raceId'
      path: '/admin/races/$raceId'
      fullPath: '/admin/races/$raceId'
      preLoaderRoute: typeof AdminRacesRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  MeRoute: MeRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  LeaguesSlugRoute: LeaguesSlugRoute,
  PUsernameRoute: PUsernameRoute,
  RacesRaceIdRoute: RacesRaceIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  LeaguesIndexRoute: LeaguesIndexRoute,
  RacesIndexRoute: RacesIndexRoute,
  AdminRacesRaceIdRoute: AdminRacesRaceIdRoute,
  AdminRacesNewRoute: AdminRacesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
