/**
 * Every notable crash at the Baku City Circuit, 2016 to 2025.
 *
 * Hand-maintained repo data, in the manner of `lineUp2027.ts`: this is an
 * archive of nine completed race weekends, so it changes when a person edits
 * it, roughly once a year, and there is no table, no cron and no runtime feed
 * behind it.
 *
 * The set is **curated, not exhaustive**, and the page says so. An exhaustive
 * list is not available: race control names a turn for car-to-car collisions
 * but logs a solo wall hit as a bare red flag with no driver and no sector, so
 * a machine-built list would be silently biased toward racing incidents and
 * would misplace the circuit's danger. These rows were researched per weekend
 * and every one carries a citation.
 *
 * Inclusion: contact with a wall or another car that had a consequence, being
 * a red flag, a retirement, a stopped car or a steward's collision note.
 * Excluded: lock-ups and escape-road excursions with no contact, and purely
 * mechanical retirements. Two researched incidents were dropped for failing
 * this test and the reasons are recorded in
 * `artifacts/baku-crash-map/researched-incidents.json`.
 *
 * Corner attribution is where the car *stopped*, not where the contact began,
 * and where those differ the note says so.
 */

/** Session buckets as the map filters them. Sprint sessions fold in. */
export type BakuSession =
  | 'FP1'
  | 'FP2'
  | 'FP3'
  | 'Qualifying'
  | 'SprintQualifying'
  | 'Sprint'
  | 'Race';

export type BakuCrash = {
  id: string;
  year: number;
  /** 2016 ran as the European Grand Prix at this circuit. */
  event: string;
  session: BakuSession;
  lap?: number;
  /** Three-letter codes for every car involved. */
  drivers: readonly string[];
  /**
   * Corner 1-20, or null when no source names one. A null is listed in the
   * table but cannot be placed on the map.
   */
  corner: number | null;
  outcome: 'red-flag' | 'dnf' | 'continued';
  /**
   * `high` = corner named by a cited report or by race control.
   * `medium` = sourced, but the corner is unnamed or sources disagree.
   */
  confidence: 'high' | 'medium';
  note: string;
  /** Required. An uncited incident does not go in this file. */
  source: string;
};

/**
 * The drivers in this archive: how their name is written, and where they raced
 * from.
 *
 * For reading, not for the roster. It holds whoever appears below, including
 * drivers who left Formula 1 years ago, and it is not a source of truth for who
 * races now. Casing follows house style rather than the timing feed's shouted
 * surnames.
 *
 * `country` is an ISO 3166-1 alpha-2 code matching the assets in
 * `public/flags`. Three of them have no asset: `se`, `pl` and `ru`. The `Flag`
 * component hides a missing file rather than showing a broken image and keeps
 * the space, so those rows stay aligned and simply carry no flag. Russia in
 * particular is an editorial call rather than a missing download.
 */
export type BakuDriver = {
  name: string;
  /** ISO 3166-1 alpha-2, lowercase, matching `public/flags/<code>.svg`. */
  country: string;
};

export const BAKU_DRIVERS: Readonly<Record<string, BakuDriver>> = {
  ALB: { name: 'Alexander Albon', country: 'th' },
  ALO: { name: 'Fernando Alonso', country: 'es' },
  BEA: { name: 'Oliver Bearman', country: 'gb' },
  BOT: { name: 'Valtteri Bottas', country: 'fi' },
  COL: { name: 'Franco Colapinto', country: 'ar' },
  DEV: { name: 'Nyck de Vries', country: 'nl' },
  ERI: { name: 'Marcus Ericsson', country: 'se' },
  GAS: { name: 'Pierre Gasly', country: 'fr' },
  GIO: { name: 'Antonio Giovinazzi', country: 'it' },
  GRO: { name: 'Romain Grosjean', country: 'fr' },
  GUT: { name: 'Esteban Gutiérrez', country: 'mx' },
  HAM: { name: 'Lewis Hamilton', country: 'gb' },
  HUL: { name: 'Nico Hülkenberg', country: 'de' },
  KUB: { name: 'Robert Kubica', country: 'pl' },
  KVY: { name: 'Daniil Kvyat', country: 'ru' },
  LEC: { name: 'Charles Leclerc', country: 'mc' },
  MAS: { name: 'Felipe Massa', country: 'br' },
  OCO: { name: 'Esteban Ocon', country: 'fr' },
  PER: { name: 'Sergio Pérez', country: 'mx' },
  PIA: { name: 'Oscar Piastri', country: 'au' },
  RAI: { name: 'Kimi Räikkönen', country: 'fi' },
  RIC: { name: 'Daniel Ricciardo', country: 'au' },
  RUS: { name: 'George Russell', country: 'gb' },
  SAI: { name: 'Carlos Sainz', country: 'es' },
  SAR: { name: 'Logan Sargeant', country: 'us' },
  SIR: { name: 'Sergey Sirotkin', country: 'ru' },
  STR: { name: 'Lance Stroll', country: 'ca' },
  TSU: { name: 'Yuki Tsunoda', country: 'jp' },
  VER: { name: 'Max Verstappen', country: 'nl' },
  VET: { name: 'Sebastian Vettel', country: 'de' },
  WEH: { name: 'Pascal Wehrlein', country: 'de' },
};

export const BAKU_CRASHES: readonly BakuCrash[] = [
  {
    id: '2016-fp1-hamilton-t3',
    year: 2016,
    event: 'European Grand Prix',
    session: 'FP1',
    drivers: ['HAM'],
    corner: 3,
    outcome: 'continued',
    confidence: 'medium',
    note: 'Touched the barrier at Turn 3.',
    source: 'https://en.wikipedia.org/wiki/2016_European_Grand_Prix',
  },
  {
    id: '2016-fp1-ricciardo-t15',
    year: 2016,
    event: 'European Grand Prix',
    session: 'FP1',
    drivers: ['RIC'],
    corner: 15,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Crashed at the exit of Turn 15 and lost a rear wheel, bringing an 11-minute red flag.',
    source: 'https://en.wikipedia.org/wiki/2016_European_Grand_Prix',
  },
  {
    id: '2016-fp2-gutierrez-t8',
    year: 2016,
    event: 'European Grand Prix',
    session: 'FP2',
    drivers: ['GUT'],
    corner: 8,
    outcome: 'continued',
    confidence: 'medium',
    note: 'Touched the barrier at Turn 8 in the castle section.',
    source: 'https://en.wikipedia.org/wiki/2016_European_Grand_Prix',
  },
  {
    id: '2016-fp3-massa-wall',
    year: 2016,
    event: 'European Grand Prix',
    session: 'FP3',
    drivers: ['MAS'],
    corner: null,
    outcome: 'continued',
    confidence: 'medium',
    note: 'Made contact with the wall and later rejoined. No contemporary report names the corner, so this is listed but not placed on the map.',
    source: 'https://en.wikipedia.org/wiki/2016_European_Grand_Prix',
  },
  {
    id: '2016-fp3-perez-t15',
    year: 2016,
    event: 'European Grand Prix',
    session: 'FP3',
    drivers: ['PER'],
    corner: 15,
    outcome: 'red-flag',
    confidence: 'high',
    note: "Lost the rear at Turn 15 at the end of the session, in what Formula 1 called a near carbon copy of Ricciardo's crash there on Friday. The gearbox change earned him a five-place grid penalty.",
    source:
      'https://www.formula1.com/en/latest/article/perez-facing-baku-grid-drop-after-fp3-crash.IVCSbgBN6AC05Q2wKqu4A',
  },
  {
    id: '2016-quali-hamilton',
    year: 2016,
    event: 'European Grand Prix',
    session: 'Qualifying',
    drivers: ['HAM'],
    corner: 11,
    outcome: 'red-flag',
    confidence: 'medium',
    note: 'Crashed in Q3 after taking the escape road at Turn 15 in both earlier segments, breaking the front suspension and bringing a red flag. Started tenth. Sources disagree on the corner: motorsport.com says Turn 11, Wikipedia Turn 10, another account Turn 9. All three are in the narrow castle-adjacent section; Turn 11 is used here as the most specific attribution.',
    source:
      'https://www.motorsport.com/f1/news/nico-rosberg-on-pole-in-baku-as-lewis-hamilton-crashes-out-of-qualifying/3221175/',
  },
  {
    id: '2016-race-gutierrez-l1',
    year: 2016,
    event: 'European Grand Prix',
    session: 'Race',
    lap: 1,
    drivers: ['GUT', 'HUL'],
    corner: null,
    outcome: 'continued',
    confidence: 'medium',
    note: "Damaged his front wing against Hulkenberg's rear on the opening lap. Corner not named in any source found, so this is listed but not placed.",
    source: 'https://en.wikipedia.org/wiki/2016_European_Grand_Prix',
  },
  {
    id: '2017-fp2-verstappen-t1',
    year: 2017,
    event: 'Azerbaijan Grand Prix',
    session: 'FP2',
    drivers: ['VER'],
    corner: 1,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Crashed heavily into the barriers at Turn 1 in the closing stages of FP2.',
    source: 'https://en.wikipedia.org/wiki/2017_Azerbaijan_Grand_Prix',
  },
  {
    id: '2017-quali-ricciardo',
    year: 2017,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['RIC'],
    corner: 6,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Slid into the wall at the exit of Turn 6 with 3m33s left in Q3, bringing a red flag, and started tenth. He won the race from there. Wikipedia places this in Q1, which cannot be right given he qualified tenth.',
    source:
      'https://www.formula1.com/en/results/2017/races/966/azerbaijan/qualifying',
  },
  {
    id: '2017-race-bottas-raikkonen-t3',
    year: 2017,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 1,
    drivers: ['BOT', 'RAI'],
    corner: 3,
    outcome: 'continued',
    confidence: 'high',
    note: "Collided at Turn 3 on the opening lap, puncturing Bottas's front right.",
    source: 'https://en.wikipedia.org/wiki/2017_Azerbaijan_Grand_Prix',
  },
  {
    id: '2017-race-ericsson-wehrlein',
    year: 2017,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    drivers: ['ERI', 'WEH'],
    corner: null,
    outcome: 'continued',
    confidence: 'medium',
    note: 'Sauber team-mates collided fighting for tenth, both continued.',
    source: 'https://en.wikipedia.org/wiki/2017_Azerbaijan_Grand_Prix',
  },
  {
    id: '2017-race-hulkenberg-wall',
    year: 2017,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 25,
    drivers: ['HUL'],
    corner: 7,
    outcome: 'dnf',
    confidence: 'high',
    note: "Clipped the inside of Turn 7 while running fifth and broke the front-right suspension, retiring on lap 25. Renault's own race notes give Turn 7; one other account says Turn 15.",
    source: 'https://www.pitpass.com/59442/Azerbaijan-GP-Race-notes-Renault',
  },
  {
    id: '2017-race-ocon-perez',
    year: 2017,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 20,
    drivers: ['OCO', 'PER'],
    corner: null,
    outcome: 'dnf',
    confidence: 'medium',
    note: 'Force India team-mates collided and left debris across the track. Pérez retired with front wing and wishbone damage.',
    source: 'https://en.wikipedia.org/wiki/2017_Azerbaijan_Grand_Prix',
  },
  {
    id: '2017-race-vettel-hamilton',
    year: 2017,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 19,
    drivers: ['VET', 'HAM'],
    corner: null,
    outcome: 'continued',
    confidence: 'high',
    note: "Vettel ran into the back of Hamilton behind the safety car, then drew alongside and swerved into him. The most-discussed incident in the circuit's history.",
    source: 'https://en.wikipedia.org/wiki/2017_Azerbaijan_Grand_Prix',
  },
  {
    id: '2018-race-grosjean-sc',
    year: 2018,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 43,
    drivers: ['GRO'],
    corner: 15,
    outcome: 'dnf',
    confidence: 'high',
    note: 'Weaving to warm his tyres behind the safety car, he knocked a switch two positions and locked the rears under braking on the run down to Turn 15, spinning into the wall from sixth place. He was the only car to crash out of a race while not racing.',
    source:
      'https://www.formula1.com/en/latest/article/grosjean-blames-accidental-switch-bump-for-safety-car-crash.6xSKdQvIreCcEW0OIIs8Is',
  },
  {
    id: '2018-race-hulkenberg-t4',
    year: 2018,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 11,
    drivers: ['HUL'],
    corner: 4,
    outcome: 'dnf',
    confidence: 'high',
    note: 'Put the rear of the car into the wall at Turn 4 and retired.',
    source: 'https://en.wikipedia.org/wiki/2018_Azerbaijan_Grand_Prix',
  },
  {
    id: '2018-race-perez-raikkonen-t2',
    year: 2018,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 1,
    drivers: ['PER', 'RAI'],
    corner: 2,
    outcome: 'continued',
    confidence: 'high',
    note: "Perez struck Raikkonen's rear at Turn 2 under the safety car.",
    source: 'https://en.wikipedia.org/wiki/2018_Azerbaijan_Grand_Prix',
  },
  {
    id: '2018-race-raikkonen-ocon-t2',
    year: 2018,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 1,
    drivers: ['RAI', 'OCO'],
    corner: 2,
    outcome: 'continued',
    confidence: 'high',
    note: 'Made contact at Turn 2 during the standing start sequence.',
    source: 'https://en.wikipedia.org/wiki/2018_Azerbaijan_Grand_Prix',
  },
  {
    id: '2018-race-raikkonen-ocon-t3',
    year: 2018,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 1,
    drivers: ['RAI', 'OCO'],
    corner: 3,
    outcome: 'dnf',
    confidence: 'high',
    note: "Collided a second time at Turn 3, with damage sufficient to force Ocon's immediate retirement.",
    source: 'https://en.wikipedia.org/wiki/2018_Azerbaijan_Grand_Prix',
  },
  {
    id: '2018-race-sirotkin-alonso-hulkenberg',
    year: 2018,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 1,
    drivers: ['SIR', 'ALO', 'HUL'],
    corner: 2,
    outcome: 'continued',
    confidence: 'high',
    note: 'Sirotkin collided with Alonso and Hülkenberg on the straight after Turn 2, double-puncturing Alonso. Safety car deployed.',
    source: 'https://en.wikipedia.org/wiki/2018_Azerbaijan_Grand_Prix',
  },
  {
    id: '2018-race-verstappen-ricciardo',
    year: 2018,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 40,
    drivers: ['VER', 'RIC'],
    corner: 1,
    outcome: 'dnf',
    confidence: 'high',
    note: 'Ricciardo went for the inside at Turn 1 on lap 40 after being overcut; Verstappen moved late in the braking zone and Ricciardo hit the back of him. Both retired, both were reprimanded, and both were made to apologise to the team.',
    source:
      'https://www.skysports.com/f1/news/12433/11352821/max-verstappen-daniel-ricciardo-reprimanded-for-all-red-bull-azerbaijan-gp-crash',
  },
  {
    id: '2019-fp1-russell-drain',
    year: 2019,
    event: 'Azerbaijan Grand Prix',
    session: 'FP1',
    drivers: ['RUS'],
    corner: 2,
    outcome: 'red-flag',
    confidence: 'high',
    note: "Destroyed the car on a loose drain cover between Turns 2 and 3, loosened moments earlier by Leclerc's Ferrari. The session was cancelled and the chassis replaced. Track furniture rather than a wall, and a judgement call for the inclusion rules.",
    source: 'https://en.wikipedia.org/wiki/2019_Azerbaijan_Grand_Prix',
  },
  {
    id: '2019-fp2-kvyat-t7',
    year: 2019,
    event: 'Azerbaijan Grand Prix',
    session: 'FP2',
    drivers: ['KVY'],
    corner: 7,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Crashed at Turn 7 with 25 minutes to go.',
    source: 'https://en.wikipedia.org/wiki/2019_Azerbaijan_Grand_Prix',
  },
  {
    id: '2019-fp2-stroll-t2',
    year: 2019,
    event: 'Azerbaijan Grand Prix',
    session: 'FP2',
    drivers: ['STR'],
    corner: 2,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Crashed at Turn 2 fifteen minutes into the session.',
    source: 'https://en.wikipedia.org/wiki/2019_Azerbaijan_Grand_Prix',
  },
  {
    id: '2019-quali-kubica-t8',
    year: 2019,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['KUB'],
    corner: 8,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Crashed into the Turn 8 wall, ending Q1.',
    source: 'https://en.wikipedia.org/wiki/2019_Azerbaijan_Grand_Prix',
  },
  {
    id: '2019-quali-leclerc-t8',
    year: 2019,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['LEC'],
    corner: 8,
    outcome: 'red-flag',
    confidence: 'high',
    note: "Fastest in all three practice sessions, then locked up into Turn 8 in Q2 and hit the same wall Kubica had. Radioed 'I am stupid, I am stupid'. The kerbs at this corner were changed before the 2021 race.",
    source:
      'https://www.racefans.net/2021/06/03/leclerc-approves-of-turn-eight-kerb-changes-at-scene-of-2019-qualifying-crash/',
  },
  {
    id: '2019-race-ricciardo-kvyat-t3',
    year: 2019,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 33,
    drivers: ['RIC', 'KVY'],
    corner: 3,
    outcome: 'dnf',
    confidence: 'high',
    note: 'Ricciardo locked up attempting a move on Kvyat at Turn 3 and went down the escape road; both retired with collision damage.',
    source: 'https://en.wikipedia.org/wiki/2019_Azerbaijan_Grand_Prix',
  },
  {
    id: '2021-quali-giovinazzi-t15',
    year: 2021,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['GIO'],
    corner: 15,
    outcome: 'red-flag',
    confidence: 'high',
    note: "Repeated Stroll's error at the same corner minutes later, misjudging the kerb.",
    source: 'https://en.wikipedia.org/wiki/2021_Azerbaijan_Grand_Prix',
  },
  {
    id: '2021-quali-ricciardo-t3',
    year: 2021,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['RIC'],
    corner: 3,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Carried too much speed into Turn 3 in Q2.',
    source:
      'https://www.racefans.net/2021/06/05/tsunoda-and-sainz-explain-double-crash-which-ended-qualifying/',
  },
  {
    id: '2021-quali-sainz-t3',
    year: 2021,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['SAI'],
    corner: 3,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Following Tsunoda, was distracted by the crash ahead and lost the Ferrari into the same corner seconds later. Ended qualifying and handed Leclerc pole.',
    source:
      'https://www.racefans.net/2021/06/05/tsunoda-and-sainz-explain-double-crash-which-ended-qualifying/',
  },
  {
    id: '2021-quali-stroll-t15',
    year: 2021,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['STR'],
    corner: 15,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Clipped the wall at Turn 15 minutes into Q1, bringing the first of four red flags.',
    source: 'https://en.wikipedia.org/wiki/2021_Azerbaijan_Grand_Prix',
  },
  {
    id: '2021-quali-tsunoda-t3',
    year: 2021,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['TSU'],
    corner: 3,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Braked too late on his first Q3 run, locked up and hit the wall at Turn 3.',
    source:
      'https://www.racefans.net/2021/06/05/tsunoda-and-sainz-explain-double-crash-which-ended-qualifying/',
  },
  {
    id: '2021-race-stroll-t20',
    year: 2021,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 30,
    drivers: ['STR'],
    corner: 20,
    outcome: 'dnf',
    confidence: 'high',
    note: 'Left-rear tyre failure exiting Turn 20 onto the main straight, into the barriers. Safety car.',
    source: 'https://en.wikipedia.org/wiki/2021_Azerbaijan_Grand_Prix',
  },
  {
    id: '2021-race-verstappen-straight',
    year: 2021,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 46,
    drivers: ['VER'],
    corner: 20,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Left-rear tyre failure on the main straight while leading with five laps to go. Red flag. Placed at Turn 20 because the failure came on the run out of it; the impact was on the straight itself.',
    source: 'https://en.wikipedia.org/wiki/2021_Azerbaijan_Grand_Prix',
  },
  {
    id: '2022-quali-stroll-t2',
    year: 2022,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['STR'],
    corner: 2,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Hit the barrier again moments later at Turn 2 and much harder, breaking the front wing and suspension. Red flag.',
    source: 'https://en.wikipedia.org/wiki/2022_Azerbaijan_Grand_Prix',
  },
  {
    id: '2022-quali-stroll-t7',
    year: 2022,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['STR'],
    corner: 7,
    outcome: 'continued',
    confidence: 'high',
    note: 'Locked up and hit the barrier at low speed at Turn 7, then reversed and carried on.',
    source: 'https://en.wikipedia.org/wiki/2022_Azerbaijan_Grand_Prix',
  },
  {
    id: '2022-quali-vettel-t15',
    year: 2022,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['VET'],
    corner: 15,
    outcome: 'continued',
    confidence: 'high',
    note: 'Locked up and hit the barrier at low speed at Turn 15 in Q2. Car undamaged.',
    source: 'https://en.wikipedia.org/wiki/2022_Azerbaijan_Grand_Prix',
  },
  {
    id: '2023-quali-devries-t3',
    year: 2023,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['DEV'],
    corner: 3,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Locked up at Turn 3 and crashed into the wall, damaging the suspension. First red flag.',
    source: 'https://en.wikipedia.org/wiki/2023_Azerbaijan_Grand_Prix',
  },
  {
    id: '2023-quali-gasly-t3',
    year: 2023,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['GAS'],
    corner: 3,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Hit the wall at the same corner, bringing the second red flag.',
    source:
      'https://www.formula1.com/en/video/2023-azerbaijan-gp-qualifying-gasly-brings-out-second-red-flag-in-q1-after-turn-3-crash.1764428177119979680',
  },
  {
    id: '2023-race-devries-t6',
    year: 2023,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 10,
    drivers: ['DEV'],
    corner: 6,
    outcome: 'dnf',
    confidence: 'high',
    note: 'Clipped the inside wall at Turn 5 and came to a stop at Turn 6. Attributed to Turn 6, where the car stopped. Safety car.',
    source: 'https://en.wikipedia.org/wiki/2023_Azerbaijan_Grand_Prix',
  },
  {
    id: '2023-sprint-tsunoda-t13',
    year: 2023,
    event: 'Azerbaijan Grand Prix',
    session: 'Sprint',
    lap: 3,
    drivers: ['TSU'],
    corner: 13,
    outcome: 'dnf',
    confidence: 'high',
    note: 'Hit the wall at Turn 13, stripping the rear-left tyre off the car. Retired with suspension damage.',
    source: 'https://en.wikipedia.org/wiki/2023_Azerbaijan_Grand_Prix',
  },
  {
    id: '2023-sprintq-sargeant-t15',
    year: 2023,
    event: 'Azerbaijan Grand Prix',
    session: 'SprintQualifying',
    drivers: ['SAR'],
    corner: 15,
    outcome: 'red-flag',
    confidence: 'high',
    note: "Hit the wall rear-first at Turn 15, damaging suspension and rear wing, and withdrew from the sprint. Baku's only sprint weekend to date.",
    source: 'https://en.wikipedia.org/wiki/2023_Azerbaijan_Grand_Prix',
  },
  {
    id: '2024-fp1-colapinto-t4',
    year: 2024,
    event: 'Azerbaijan Grand Prix',
    session: 'FP1',
    drivers: ['COL'],
    corner: 4,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Crashed into the barriers at Turn 4 on his first Baku weekend.',
    source: 'https://en.wikipedia.org/wiki/2024_Azerbaijan_Grand_Prix',
  },
  {
    id: '2024-fp1-leclerc-t15',
    year: 2024,
    event: 'Azerbaijan Grand Prix',
    session: 'FP1',
    drivers: ['LEC'],
    corner: 15,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Crashed at Turn 15.',
    source: 'https://en.wikipedia.org/wiki/2024_Azerbaijan_Grand_Prix',
  },
  {
    id: '2024-fp3-bearman-t1',
    year: 2024,
    event: 'Azerbaijan Grand Prix',
    session: 'FP3',
    drivers: ['BEA'],
    corner: 1,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Overcooked the braking into Turn 1 and hit the wall side-on, damaging the front left.',
    source:
      'https://www.formula1.com/en/latest/article/watch-bearman-smacks-the-wall-in-baku-to-bring-out-red-flags-in-fp3.7pHwREohYCijIpwVue5Y9k',
  },
  {
    id: '2024-fp3-verstappen-t15',
    year: 2024,
    event: 'Azerbaijan Grand Prix',
    session: 'FP3',
    drivers: ['VER'],
    corner: 15,
    outcome: 'red-flag',
    confidence: 'medium',
    note: 'Locked up into Turn 15 and slid into the barriers, bringing out a red flag.',
    source:
      'https://www.formula1.com/en/latest/article/fp3-gasly-leads-perez-in-final-azerbaijan-gp-practice-as-verstappen-crashes.7ogGtjQ3t77ZElcZu1F1Uv',
  },
  {
    id: '2024-race-perez-sainz',
    year: 2024,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 50,
    drivers: ['PER', 'SAI'],
    corner: 3,
    outcome: 'dnf',
    confidence: 'high',
    note: 'Contact on the straight between Turns 2 and 3 while disputing the podium on the penultimate lap; both hit the barrier and retired. Stewards found neither predominantly to blame. Race control logged it as a Turn 2 incident, which is where it originated; the map places it at Turn 3, where the cars ended up.',
    source:
      'https://www.motorsport.com/f1/news/perez-and-sainz-crash-out-on-penultimate-lap-azerbaijan-gp/10654536/',
  },
  {
    id: '2024-race-tsunoda',
    year: 2024,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 1,
    drivers: ['TSU', 'STR'],
    corner: null,
    outcome: 'dnf',
    confidence: 'medium',
    note: "Took a hole in the sidepod in first-lap contact with Stroll, ran on with no performance and retired on lap 14, the race's first retirement. Corner not named in any source found.",
    source:
      'https://www.gpfans.com/us/f1-news/1030225/f1-azerbaijan-gp-yuki-tsunoda-rb-out/',
  },
  {
    id: '2025-quali-albon-t1',
    year: 2025,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['ALB'],
    corner: 1,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Clipped the inside wall with the front left at Turn 1 in Q1, breaking the steering rack.',
    source:
      'https://www.motorsport.com/f1/news/six-shunts-how-azerbaijan-gp-qualifying-broke-a-red-flag-f1-record/10761085/',
  },
  {
    id: '2025-quali-bearman-t2',
    year: 2025,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['BEA'],
    corner: 2,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'The rear stepped out at Turn 2 in Q2 and he struck the barrier, breaking the suspension.',
    source:
      'https://www.motorsport.com/f1/news/six-shunts-how-azerbaijan-gp-qualifying-broke-a-red-flag-f1-record/10761085/',
  },
  {
    id: '2025-quali-colapinto-t4',
    year: 2025,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['COL'],
    corner: 4,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Lost the front end at Turn 4 and hit the wall rear-first.',
    source:
      'https://www.motorsport.com/f1/news/six-shunts-how-azerbaijan-gp-qualifying-broke-a-red-flag-f1-record/10761085/',
  },
  {
    id: '2025-quali-hulkenberg-t4',
    year: 2025,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['HUL'],
    corner: 4,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Locked up and hit the Tecpro barrier at Turn 4, breaking the front wing and inflicting heavy floor damage.',
    source:
      'https://www.motorsport.com/f1/news/six-shunts-how-azerbaijan-gp-qualifying-broke-a-red-flag-f1-record/10761085/',
  },
  {
    id: '2025-quali-leclerc-t15',
    year: 2025,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['LEC'],
    corner: 15,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Locked up under braking for Turn 15 in Q3 and hit the barrier.',
    source:
      'https://www.motorsport.com/f1/news/six-shunts-how-azerbaijan-gp-qualifying-broke-a-red-flag-f1-record/10761085/',
  },
  {
    id: '2025-quali-piastri-t3',
    year: 2025,
    event: 'Azerbaijan Grand Prix',
    session: 'Qualifying',
    drivers: ['PIA'],
    corner: 3,
    outcome: 'red-flag',
    confidence: 'high',
    note: 'Missed the apex on a flying lap in Q3 and struck the barrier. Sixth red flag of the session, a Formula 1 record.',
    source:
      'https://www.motorsport.com/f1/news/six-shunts-how-azerbaijan-gp-qualifying-broke-a-red-flag-f1-record/10761085/',
  },
  {
    id: '2025-race-albon-colapinto',
    year: 2025,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 16,
    drivers: ['ALB', 'COL'],
    corner: 5,
    outcome: 'continued',
    confidence: 'high',
    note: "Came together with Colapinto at Turn 5 shortly after both pitted, spinning the Alpine, which recovered. Albon took a ten-second penalty and accepted blame. Formula 1's own race report and race control agree on Turn 5; Wikipedia's Turn 7 is wrong.",
    source:
      'https://www.formula1.com/en/latest/article/verstappen-claims-dominant-azerbaijan-win-over-russell-and-sainz-after.gT4fbKTwpl3dI79nDmrHS',
  },
  {
    id: '2025-race-hulkenberg-ocon-t6',
    year: 2025,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 6,
    drivers: ['HUL', 'OCO'],
    corner: 6,
    outcome: 'continued',
    confidence: 'high',
    note: 'Collided at Turn 6 and both continued; stewards reviewed with no further action. No contemporary report covers it, so the FIA race control log is the citation.',
    source: 'openf1:race_control:9904',
  },
  {
    id: '2025-race-piastri-t6',
    year: 2025,
    event: 'Azerbaijan Grand Prix',
    session: 'Race',
    lap: 1,
    drivers: ['PIA'],
    corner: 6,
    outcome: 'dnf',
    confidence: 'medium',
    note: "Jumped the start, dropped to last, then went into the barriers on the opening lap for his first retirement of the season. Formula 1's race report puts the impact at Turn 5; race control logged the recovery vehicle at Turn 6, which is where the car came to rest and where this map places it.",
    source:
      'https://www.formula1.com/en/latest/article/verstappen-claims-dominant-azerbaijan-win-over-russell-and-sainz-after.gT4fbKTwpl3dI79nDmrHS',
  },
];
