/**
 * Baku City Circuit geometry, for the crash map on the Azerbaijan write-up.
 *
 * GENERATED by `scripts/generate-baku-geometry.mts`. Do not edit by hand:
 * regenerate instead, or the outline and the corner positions drift apart.
 *
 * Coordinates are display units inside `viewBox`, already rotated to the
 * orientation people recognise and flipped for SVG's downward y axis. The
 * source trace came from the circuit outline OpenF1 links to, fetched once and
 * committed; nothing here calls a network at build or run time.
 *
 * There is no separate full-lap path. The segments below already trace every
 * point of the lap between them, so drawing them all in the base colour is the
 * outline; shipping a second copy of the same coordinates was pure weight.
 */

export const BAKU_VIEW_BOX = { width: 1000, height: 710 } as const;

/**
 * A stretch of track owned by one corner, being the run of the lap closer to
 * that corner than to any other. The crash map strokes each stretch by how
 * many incidents its corner has collected, so these are the heat bands.
 */
export type BakuTrackSegment = {
  /** Corner number, 1-20. */
  corner: number;
  /** SVG path data for this stretch. */
  d: string;
};

export const BAKU_TRACK_SEGMENTS: readonly BakuTrackSegment[] = [
  {
    corner: 1,
    d: 'M816 243L897 213L916 207L923 203L925 200L927 196L928 189L927 183L916 156L887 79',
  },
  { corner: 2, d: 'M887 79L884 74L882 72L877 72L868 73L743 113L641 151' },
  {
    corner: 3,
    d: 'M641 151L573 177L559 183L552 187L550 190L550 192L550 195L558 214L564 236',
  },
  {
    corner: 4,
    d: 'M564 236L572 256L575 265L575 269L575 273L575 276L573 278L571 280L565 283L546 289L519 299L509 303',
  },
  { corner: 5, d: 'M509 303L464 326L459 330L457 333L454 339L455 345L459 353' },
  { corner: 6, d: 'M459 353L459 356L458 359L455 363L437 374' },
  { corner: 20, d: 'M437 374L340 441' },
  { corner: 19, d: 'M340 441L332 445' },
  { corner: 7, d: 'M332 445L327 446L325 445L322 442L321 438L317 426L305 374' },
  { corner: 8, d: 'M305 374L302 368L289 362' },
  { corner: 10, d: 'M289 362L284 361L271 359' },
  { corner: 11, d: 'M271 359L264 356L261 353L260 351L260 348' },
  {
    corner: 12,
    d: 'M260 348L260 341L258 337L254 335L246 334L234 335L227 337L199 348L158 365',
  },
  { corner: 13, d: 'M158 365L114 387L105 396L102 400L98 409L83 449' },
  { corner: 14, d: 'M83 449L77 468L74 489L75 532' },
  {
    corner: 15,
    d: 'M75 532L75 541L72 560L72 564L73 567L75 570L77 571L122 598L178 633',
  },
  {
    corner: 16,
    d: 'M178 633L185 636L191 638L194 638L199 637L202 635L205 631L230 588',
  },
  { corner: 17, d: 'M230 588L240 574L247 565L255 557L284 534' },
  { corner: 18, d: 'M284 534L297 522L308 512L312 508L317 500L320 494L325 480' },
  { corner: 19, d: 'M325 480L331 459L334 453L340 446L350 437L366 427L440 376' },
  { corner: 20, d: 'M440 376L451 370L459 367' },
  { corner: 6, d: 'M459 367L566 330' },
  { corner: 4, d: 'M566 330L676 289L698 282L773 258' },
  { corner: 1, d: 'M773 258L822 241L816 243' },
];

/**
 * The start/finish line: where it sits on the main straight, and the direction
 * the lap runs at that point, in degrees clockwise from east.
 *
 * A map of a circuit with no start line and no arrow reads as an abstract
 * shape. These two marks are what make it a lap.
 */
export const BAKU_START_FINISH = {
  x: 816,
  y: 243,
  angle: -19.8,
} as const;

/** The twenty numbered corners, at their position on the outline above. */
export const BAKU_CORNERS: readonly { number: number; x: number; y: number }[] =
  [
    { number: 1, x: 926.2171468320989, y: 198.27712357535893 },
    { number: 2, x: 879.840501256645, y: 71.76500719614955 },
    { number: 3, x: 550.7758871043596, y: 189.04332090266678 },
    { number: 4, x: 574.806825005059, y: 275.4976363116341 },
    { number: 5, x: 455.1986139002597, y: 336.4098307292486 },
    { number: 6, x: 458.54493004234934, y: 358.8831957992683 },
    { number: 7, x: 328.3616687577375, y: 445.8629676364488 },
    { number: 8, x: 303.8267807828797, y: 371.6104237625965 },
    { number: 9, x: 296.1970275642447, y: 364.99810666771805 },
    { number: 10, x: 285.0372317680064, y: 360.8809283668607 },
    { number: 11, x: 266.30864410485816, y: 357.08891418452936 },
    { number: 12, x: 258.39299537532725, y: 336.98634122431434 },
    { number: 13, x: 108.70585323740902, y: 392.1882890626361 },
    { number: 14, x: 75.73665440103584, y: 477.32141554653265 },
    { number: 15, x: 72.74073742191828, y: 567.344886040749 },
    { number: 16, x: 198.4955214874048, y: 637.0040334725198 },
    { number: 17, x: 240.28489980596456, y: 573.1012291813487 },
    { number: 18, x: 312.10690802841395, y: 508.4136618079436 },
    { number: 19, x: 335.63862898719447, y: 450.7635060601775 },
    { number: 20, x: 438.8976156890394, y: 377.2552075395098 },
  ];
