/**
 * Sepang International Circuit geometry, for the lap map on the 2026 Bahrain
 * Grand Prix write-up.
 *
 * GENERATED by `scripts/generate-sepang-geometry.mts`. Do not edit by hand:
 * the outline is © OpenStreetMap contributors (ODbL), and the markers are
 * declared as metres after the line in that script.
 */

export const SEPANG_VIEW_BOX = { width: 1000, height: 846 } as const;

/** Sectors 1, 2 and 3, in lap order. Between them they trace the whole lap. */
export const SEPANG_SECTORS: readonly [string, string, string] = [
  'M549 437L76 436L66 434L59 431L55 427L51 422L49 417L48 412L48 407L49 400L51 395L57 387L62 383L67 381L72 380L79 381L85 383L109 394L115 395L119 395L125 394L129 391L133 385L134 379L134 372L133 365L130 358L111 330L106 319L102 308L101 299L100 287L101 269L102 252L108 228L112 214L117 201L125 186L135 173L146 163L159 153L174 144L189 138L204 133L273 117L332 102L400 81',
  'M400 81L438 70L498 48L504 48L507 49L511 51L515 58L516 62L520 112L534 234L536 244L539 255L544 265L550 275L557 284L565 292L576 300L590 308L608 314L626 316L640 315L653 312L663 308L676 302L685 296L701 280L710 273L720 267L732 263L745 259L758 259L772 260L785 265L798 272L810 282L820 293L947 467L951 473L952 478L952 483L950 489L921 546L918 550L914 554L909 557L902 558L806 556L744 555L643 558L550 563L543 564L539 567L536 569L535 572L534 576L535 581L537 586L585 621L592 627L597 633L598 635',
  'M598 635L604 646L607 658L608 668L608 680L607 694L605 707L600 728L595 739L588 753L579 769L563 789L554 796L545 798L536 798L530 796L522 792L370 644L362 638L350 633L342 632L330 633L319 636L263 660L252 663L230 665L215 665L201 663L180 657L163 648L147 637L128 616L122 604L119 590L119 581L121 575L124 570L130 564L137 561L242 550L670 509L737 503L803 496L812 493L820 488L824 482L828 474L827 463L825 454L821 449L815 444L806 440L796 439L662 438L549 437',
];

/** Straight-mode zones, beside the track on the left of travel. */
export const SEPANG_STRAIGHT_MODE_ZONES: readonly string[] = [
  'M216 113L269 101L328 85L418 59L446 48',
  'M845 574L745 572L643 575L608 577',
  'M198 537L668 492L735 486L799 479',
  'M723 456L548 454L313 453L123 453',
];

/** Turn badge centres, outside the lap beside each apex. */
export const SEPANG_CORNERS: readonly {
  number: number;
  x: number;
  y: number;
}[] = [
  { number: 1, x: 44, y: 359 },
  { number: 2, x: 163, y: 362 },
  { number: 3, x: 132, y: 136 },
  { number: 4, x: 496, y: 81 },
  { number: 5, x: 612, y: 284 },
  { number: 6, x: 783, y: 233 },
  { number: 7, x: 975, y: 506 },
  { number: 8, x: 892, y: 588 },
  { number: 9, x: 518, y: 609 },
  { number: 10, x: 633, y: 637 },
  { number: 11, x: 541, y: 768 },
  { number: 12, x: 324, y: 666 },
  { number: 13, x: 196, y: 630 },
  { number: 14, x: 130, y: 532 },
  { number: 15, x: 845, y: 430 },
];

/** The line, and the direction of travel there in degrees clockwise from east. */
export const SEPANG_START_FINISH = {
  x: 549,
  y: 437,
  angle: -179.9,
} as const;

export const SEPANG_SPEED_TRAP = { x: 669, y: 509 } as const;

export const SEPANG_OVERTAKE = {
  detection: { x: 812, y: 442 },
  activation: { x: 773, y: 439 },
} as const;
